### ISSUE TITLE
Two InjectableManaged objects where one depends on the other?

### ISSUE THREAD

**Issue by jaxley** [dragonzone/dropwizard-hk2#17]
I tried creating two InjectableManaged objects where one (A) takes the other (B) as a constructor parameter, but whenever A is being constructed, it throws a MultiException claiming that it can't find B.  I've stepped through and see the constructor of B invoked, but somehow it doesn't end up registered in time to be used to construct class A.

Perhaps there's some sort of timing issue?  Can you think of anything that could be preventing this from working as expected? 

If I instantiate one of the classes without the other, it works fine and the start() method gets called.  But it's not available to HK2 somehow when the other object is being constructed.

**Comment by baharclerode** [comment]
Unfortunately, Jersey will only bind to the `InjectableManaged` contract; If you're trying to inject B into another class, you can try the following:

* Explicitly bind to both contracts:
    
    ```java
    bind(B.class).to(B.class).to(InjectableManaged.class).in(Singleton.class); // bindAsContract(B.class).to(InjectableManaged.class).in(Singleton.class) also works
    ```
    instead of `environment.jersey().register(B.class);
* Mark `B` as a component to Jersey by adding the `@Provider` annotation.
