### ISSUE TITLE
Support of Dropwizard 3.0

### ISSUE THREAD

**Issue by pbelousov** [dragonzone/dropwizard-hk2#25]
Hey there, are you going to support Dropwizard 3.x?
For some reason, currently, we cannot upgrade our applications to Dropwizard 4.x, and the `dropwizard-hk2` module is the only one that we cannot use for DW 3.0. So if you have any plans to release the module for DW v3, we would be really appreciative!  

Thank you!

**Comment by baharclerode** [comment]
I will look into that! I don't think it'll be too difficult to backport.

**Comment by baharclerode** [comment]
So, the changes weren't too difficult, but finding the time apparently was 🙄 

I've released the [3.0.0](https://github.com/dragonzone/dropwizard-hk2/releases/tag/dropwizard-hk2-3.0.0) tag-- let me know if there are any issues/problems with it!

**Comment by pbelousov** [comment]
Thank you, Bryan! 🙏 
We will start using this version and let you know in case of any issues!
